Azure Github Actions - Create separate GitHub Actions for Unit Test and E2E Deployment
IBM/zmodstack-deploy pull request #82
Opened 2023-11-08 12:52 UTC by midhun6989

Related to the [issue](https://github.com/IBM/zmodstack-deploy/issues/77).

2023-11-10 19:32 UTC, ivandov requested changes
Looks good, but no reason to have duplicated jobs/steps between the two azure github actions. Please remove any of the steps that you've copied over into the new action from the old action, and also remove the `branches-ignore` from the new action.

2023-11-11 06:54 UTC, midhun6989 commented
> Looks good, but no reason to have duplicated jobs/steps between the two azure github actions. Please remove any of the steps that you've copied over into the new action from the old action, and also remove the `branches-ignore` from the new action.

@ivandov Updated as mentioned.

2023-11-20 16:06 UTC, ivandov approved these changes
LGTM

2023-11-21 06:15 UTC, midhun6989 commented on .github/workflows/azure-test.yml
> +      - release-*.*.*
Updated.

2023-11-21 06:19 UTC, midhun6989 commented on .github/workflows/azure-test.yml
> +name: Azure Test
Updated.

2023-11-21 06:20 UTC, midhun6989 commented on .github/workflows/azure-test.yml
> +        workdir: ${{ env.WORK_DIR }}
Updated.

2023-11-21 07:24 UTC, merged